apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-deployment
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:latest
        ports:
        - containerPort: 3000
        - containerPort: 22
        env:
        - name: DISABLE_REGISTRATION
          value: "true"
        volumeMounts:
        - mountPath: /data
          name: gitea-data
      volumes:
      - name: gitea-data
        hostPath:
          path: /k3svol0/gitea
          type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: gitea-service
spec:
  selector:
    app: gitea
  ports:
  - name: gitea-web
    protocol: TCP
    port: 3000
  - name: gitea-ssh
    protocol: TCP
    port: 22

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gitea-ingress-secure
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`git.zuh0.com`) || Host(`gitea.zuh0.com`)
    kind: Rule
    services:
    - name: gitea-service
      port: 3000
  tls:
    certResolver: tls-challenge

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: gitea-ingress-ssh
  namespace: default
spec:
  entryPoints:
    - ssh
  routes:
  - match: HostSNI(`*`)
    kind: Rule
    services:
    - name: gitea-service
      port: 22
