apiVersion: v1
kind: Secret
metadata:
  name: ddclient-secret
  labels:
    app: ddclient
stringData:
  ddclient.conf: |
    daemon=300
    syslog=yes
    ssl=yes
    use=web, web=checkip.dyndns.com/, web-skip='IP Address'
    protocol=googledomains
    login=<FIXME>
    password=<FIXME>
    dynamic.zuh0.com

---
apiVersion: v1
kind: Secret
metadata:
  name: traefik-dashboard-secret
  labels:
    app: traefik
stringData:
  password: <FIXME>
